export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_ACTIVE_MINER_LIST = "GET_ACTIVE_MINER_LIST"
export const GET_SOLD_MINER_LIST = "GET_SOLD_MINER_LIST"
export const GET_RECENT_TRADE_LIST = "GET_RECENT_TRADE_LIST"
export const GET_MINER_TRADE_LIST = "GET_MINER_TRADE_LIST"
